/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/main': RouteRecordInfo<'/main', '/main', Record<never, never>, Record<never, never>>,
    '/main/duyi': RouteRecordInfo<'/main/duyi', '/main/duyi', Record<never, never>, Record<never, never>>,
    '/main/duyi/1': RouteRecordInfo<'/main/duyi/1', '/main/duyi/1', Record<never, never>, Record<never, never>>,
    '/main/homepage': RouteRecordInfo<'/main/homepage', '/main/homepage', Record<never, never>, Record<never, never>>,
    '/main/tools': RouteRecordInfo<'/main/tools', '/main/tools', Record<never, never>, Record<never, never>>,
    '/main/tools/generateQrcode': RouteRecordInfo<'/main/tools/generateQrcode', '/main/tools/generateQrcode', Record<never, never>, Record<never, never>>,
    '/three': RouteRecordInfo<'/three', '/three', Record<never, never>, Record<never, never>>,
    '/three/homepage/': RouteRecordInfo<'/three/homepage/', '/three/homepage', Record<never, never>, Record<never, never>>,
    '/three/model': RouteRecordInfo<'/three/model', '/three/model', Record<never, never>, Record<never, never>>,
    '/three/model/test': RouteRecordInfo<'/three/model/test', '/three/model/test', Record<never, never>, Record<never, never>>,
  }
}
