/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/main/dashboard': RouteRecordInfo<'/main/dashboard', '/main/dashboard', Record<never, never>, Record<never, never>>,
    '/main/dashboard/duyi': RouteRecordInfo<'/main/dashboard/duyi', '/main/dashboard/duyi', Record<never, never>, Record<never, never>>,
    '/main/dashboard/duyi/1': RouteRecordInfo<'/main/dashboard/duyi/1', '/main/dashboard/duyi/1', Record<never, never>, Record<never, never>>,
    '/main/dashboard/homepage': RouteRecordInfo<'/main/dashboard/homepage', '/main/dashboard/homepage', Record<never, never>, Record<never, never>>,
    '/main/dashboard/tools': RouteRecordInfo<'/main/dashboard/tools', '/main/dashboard/tools', Record<never, never>, Record<never, never>>,
    '/main/dashboard/tools/1': RouteRecordInfo<'/main/dashboard/tools/1', '/main/dashboard/tools/1', Record<never, never>, Record<never, never>>,
    '/three/': RouteRecordInfo<'/three/', '/three', Record<never, never>, Record<never, never>>,
    '/three//': RouteRecordInfo<'/three//', '/three', Record<never, never>, Record<never, never>>,
    '/three/model/model': RouteRecordInfo<'/three/model/model', '/three/model/model', Record<never, never>, Record<never, never>>,
    '/three/model/test/test': RouteRecordInfo<'/three/model/test/test', '/three/model/test/test', Record<never, never>, Record<never, never>>,
  }
}
